apiVersion: dscinitialization.opendatahub.io/v2
kind: DSCInitialization
metadata:
  labels:
    app.kubernetes.io/name: dscinitialization
  name: default-dsci
spec:
  applicationsNamespace: 'opendatahub'
  trustedCABundle:
    managementState: "Managed"
    customCABundle: ""
